### ISSUE TITLE
Rails 4.1.9: During migration Foreigher throw undefined method `add_foreign_key' for #<ActiveRecord::Schema:...

### ISSUE THREAD

**Issue by tangens** [matthuhiggins/foreigner#161] opened 2015-01-06 10:32 UTC
I upgraded rails from 4.1.8 to 4.1.9 and use add_foreign_key methods in migrations and schema.rb. now a get this error: NoMethodError: undefined method `add_foreign_key' for #<ActiveRecord::Schema: ...

Can some one help with this issue?

Thanks!

**Comment by thiagogsr** [comment] 2015-01-08 19:52
+1

**Comment by georgediaz88** [comment] 2015-01-08 19:52
+1 here as well

**Comment by thiagogsr** [comment] 2015-01-08 19:53
`pg 0.18.1`

**Comment by thiagogsr** [comment] 2015-01-08 19:57
http://weblog.rubyonrails.org/releases/

`Foreign Keys
Rails has long had a tumultuous relationship with foreign keys, but the drama days are now over. If you want to have foreign keys, you can have foreign keys, and Rails will still smile as it takes your order. The migration DSL gets add_foreign_key and remove_foreign_key and the standard schema.rb dumper will support maintaing these declarations. Foreign key support starts out as an exclusive to the MySQL and PostgreSQL adapters.`

**Comment by jwood** [comment] 2015-01-08 20:00
Hi @thiagogsr.  That change is for Rails 4.2.  As far as I can tell Rails 4.1.9 does not include that change.

**Comment by thiagogsr** [comment] 2015-01-08 20:01
@jwood This is true, sorry.

**Comment by georgediaz88** [comment] 2015-01-08 20:04
Maybe I'm mistaken. So, for Rails 4.1.8 this works fine. What changed that in 4.1.9 that support is now lost?

**Comment by thiagogsr** [comment] 2015-01-08 20:08
The pg gem was updated too to 0.18.1, maybe the problem is there, not in rails update. What is the yours pg version?

**Comment by georgediaz88** [comment] 2015-01-08 20:09
ah maybe. Mine is `0.13.2`. That may be why. Let me try upgrading that and report back.

**Comment by matthuhiggins** [comment] 2015-01-08 20:09
I have not had a chance to look at this. Let me know what you find.

**Comment by bopm** [comment] 2015-01-08 20:25
Same problem for mysql for me.

**Comment by jwood** [comment] 2015-01-08 20:29
Rails 4.1.9 contained changes to `db:schema:load`, which is where I am seeing this error:

https://github.com/rails/rails/blob/cca85ba699242c3266c5132dd601fdd8c5c5bb16/activerecord/CHANGELOG.md

My money is that something with that change is causing this.

**Comment by georgediaz88** [comment] 2015-01-08 20:37
That's exactly where it's breaking for me even after the `pg` gem upgrade. Not sure where to go from here.

**Comment by thiagogsr** [comment] 2015-01-08 22:06
I returned to version 0.17.1 (when it was working), but the problem keeps. So, the problem was the rails upgrade :(

**Comment by thiagogsr** [comment] 2015-01-08 22:10
The problem the method not exists. Rails changelog says `db:schema:load and db:structure:load no longer purge the database before loading the schema. This is left for the user to do.` only, so it should not break the `add_foreign_key ` method.

**Comment by guiman** [comment] 2015-01-09 13:35
Will be opening PR with solution for this shortly

**Comment by thiagogsr** [comment] 2015-01-09 13:35
Great

**Comment by guiman** [comment] 2015-01-09 14:14
@thiagogsr here https://github.com/matthuhiggins/foreigner/pull/162

**Comment by thiagogsr** [comment] 2015-01-09 14:23
I think you need change the spec to add this line, the tests are not passing. Waiting for merge :D

**Comment by georgediaz88** [comment] 2015-01-09 15:45
awesome guys. Awaiting a merge to follow soon as well. :)

**Comment by matthuhiggins** [comment] 2015-01-09 17:47
When the PR is ready, I will merge and release a gem as quickly as possible.

**Comment by guiman** [comment] 2015-01-09 17:57
I think I have an idea about how to avoid the verification of rails
version. Will amend this pr one I get near a computer :+1:

**Comment by matthuhiggins** [comment] 2015-01-10 23:18
Thanks everyone. v1.7.2 is released with the fix.

**Closed by matthuhiggins** 2015-01-10 23:18 UTC

**Comment by tangens** [comment] 2015-01-12 09:32
Thank You!

**Comment by tangens** [comment] 2015-01-12 10:06
I update Rails to 4.1.9 and Foreigner to 1.7.2 and still have the same error running  rake db:create db:schema:load

**Comment by guiman** [comment] 2015-01-12 10:07
In order to fix this, you need to first run migrate. At this point is when schema dumper adds `Foreigner.load` into the schema.rb file

--  
Alvaro Fernando Lara
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by georgediaz88** [comment] 2015-01-13 03:40
Great. Thanks for the fix guys! I updated to 4.1.9 successfully.

**Comment by richardwan** [comment] 2015-06-02 17:31
so in the .travis.yml i need to put in: db:create db:migrate db:schema:load
instead of just db:create db:schema:load
